version: '3.1'
services:
  biblioteca-db:
    image: mysql:8.0
    container_name: biblioteca-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: biblioteca12345