spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:    
    url: jdbc:mysql://localhost/biblioteca_ceiba?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username : root
    password: tolbar12345
server:
  port: 8291